services:
  - type: web
    name: tannu-jobportal
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URL
        sync: false
